### ISSUE TITLE
cannot find watchman on zsh

### ISSUE THREAD

**Issue by hiaw** [infinitered/solidarity#111]
I'm using `zsh` and can confirm that I have `watchman` installed. But `solidarity` reports that `watchman` is not installed. `applesimutils` and `ANDROID_HOME` also reported missing

    "Watchman": [
      {
        "rule": "cli",
        "binary": "watchman",
        "error": "Please install watchman on this machine. Refer to the official Watchman installation instructions for additional help.",
        "platform": [
          "darwin",
          "linux"
        ]
      }
    ],
    "Detox": [
      {
        "rule": "cli",
        "binary": "detox"
      },
      {
        "rule": "cli",
        "binary": "applesimutils",
        "error": "Try `brew install --HEAD applesimutils`",
        "platform": "darwin"
      }
    ],
    "Android": [
      {
        "rule": "cli",
        "binary": "emulator"
      },
      {
        "rule": "cli",
        "binary": "android"
      },
      {
        "rule": "env",
        "variable": "ANDROID_HOME",
        "error": "The ANDROID_HOME environment variable must be set to your local SDK.  Refer to getting started docs for help."
      }
    ],
 
The following are from the cli:

```
~/D/D ❯❯❯ which applesimutils
/usr/local/bin/applesimutils
~/D/D ❯❯❯ which watchman
/usr/local/bin/watchman
~/D/D❯❯❯ export
ANDROID_HOME=/Users/.../Library/Android/sdk
```

**Comment by GantMan** [comment]
Heya!  I also use ZSH so let's see what's up.

So you type `which` and it works, but the rules don't.   The rules use [node-which](https://github.com/npm/node-which) so they can be system independent.  

The failing ENV comes from `process.env` which isn't even a 3rd party plugin, that's supposed to work out the box with Node.

This sounds to me like Node is failing.  What version of Node are you using?  Make sure it's 7.6 or higher.  Any history of failing node CLIs in the passed?

**Comment by hiaw** [comment]
I'm using node v8.7.0. I'll try `node-which` and report back

**Comment by GantMan** [comment]
Also report back this:
![image](https://user-images.githubusercontent.com/997157/32260772-04017900-be98-11e7-8971-fc15937370cb.png)

**Comment by hiaw** [comment]
So I've tried both `node-which` and `process.env` and they seems to work find

```
~/D/D ❯❯❯ ./node_modules/which/bin/which watchman
/usr/local/bin/watchman
~/D/D/lounge7 ❯❯❯ node
> process.env.ANDROID_HOME
'/Users/.../Library/Android/sdk'
```

**Comment by GantMan** [comment]
Wow!

OK, can you you now try to use OUR code?

![image](https://user-images.githubusercontent.com/997157/32297861-919f8096-bf1e-11e7-8f1f-4c43e8453d5f.png)

**Comment by hiaw** [comment]
Looks identical. 

<img width="540" alt="screen shot 2017-11-02 at 10 10 51 am" src="https://user-images.githubusercontent.com/527296/32298104-2c093e8c-bfb6-11e7-93f6-d603a647ccf3.png">

**Comment by GantMan** [comment]
That's using our code!  So how is it failing :/  Can you screen shot the failling rules?

**Comment by GantMan** [comment]
Also, if you want we can chat in community.infinite.red and maybe even screen share.  Might help us identify an exact point of divergence.

**Comment by GantMan** [comment]
hey @hiaw - any updates on how it's failing?   Are you running from inside npm/yarn?  Let me know!  I hope to knock this out :)

**Comment by GantMan** [comment]
hey @hiaw - how's this looking?  Might close soon if you don't have an update.

**Comment by GantMan** [comment]
Going to have to close this if we're not getting updates.  Feel free to re-open.
