### ISSUE TITLE
Local install with npm doesn't work

### ISSUE THREAD

**Issue by matteo-hertel** [infinitered/solidarity#113]
Hello, 

I wanted to add solidarity to one of my projects, I have the hard constraint of using npm and not yarn, when installing solidarity `npm i -D solidarity` the package is installed but when I run it like

`./node_modules/.bin/solidarity` 

or even as part of package.jsonscript 

```
  "scripts": {
    "solidarity": "solidarity",
  },
```

it throws an error 

```
module.js:529
    throw err;
    ^

Error: Cannot find module 'window-size/utils'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (./node_modules/readline-utils/index.js:13:17)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

if I install it globally or with locally with yarn it works just fine

My Env

```
node -v
v8.6.0
npm -v
5.4.2
```

any idea why I get this problem? I also tried no install it as dependency and not devDependency, same result

**Comment by GantMan** [comment]
Hiya!  So that's odd.  It should work fine as an `npm` module.  I've tested it as such.  Maybe more tests are needed.

I believe I've seen that error once during development.   Do you have npm cache you can clear?

If the bug persists, can you try `npm i window-size`?   Which is a dependency that seems to be failing.  And let me know if that strangeness suddenly makes things work.

**Comment by matteo-hertel** [comment]
So I tested it in a vanilla project and it works, so must be something related to current set up, I'll close the issue for now as it's not related to the package, thanks for looking into it 😄
