### ISSUE TITLE
marked vulnerability

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/solidarity#160]
![image](https://user-images.githubusercontent.com/1479215/34685186-6e82d0c2-f45c-11e7-9cf3-3756e4e0455c.png)

**Comment by tabrindle** [comment]
Of note - sync-exec a dependency of envinfo (`solidarity report`) was also a vulnerability and it has since been fixed with envinfo@3.11.0

**Comment by GantMan** [comment]
This was fixed back on Jan 4th 👍 
Here: https://github.com/infinitered/solidarity/commit/8dd7d63b0d6b84e93ab3d851060fafd6902356a0
