### ISSUE TITLE
Show-Off-Gif at top of Readme.MD

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#166]
We have a great logo, a great tag line, but no show off gif.

We need a GIF showing a complex and useful solidarity check in a project.  The output of a `--verbose` perhaps?

As plugins and new features enter Solidarity, we should add to the gif.

**Comment by derekgreenberg** [comment]
I'm inspired by the well-produced gifs here: https://gfycat.com/gifs/tag/GifRecipes . Thanks to @GantMan for cluing me in to this. Watch these recipe GIFs for inspiration. For a Solidarity gif, produce as a sequence of terminal screens showing the actions along with text explanation overlays of what's going on. Surprising how much info can be packed into a short number of frames.

Production process is to generate the QT screen grabs, edit in video editor of choice, insert text explanations as overlays via the editor, then export as animated GIF. I've learned from watching https://gfycat.com/gifs/tag/GifRecipes that text + visuals can be consumed at a rapid pace.

**Comment by GantMan** [comment]
![solidarity_explainer](https://user-images.githubusercontent.com/997157/36068817-297b9e02-0ea4-11e8-96b5-9ea7a34401e2.gif)

Thoughts @derekgreenberg ?
