### ISSUE TITLE
React Native binary gives wrong version number

### ISSUE THREAD

**Issue by skellock** [infinitered/solidarity#175]
## Problem

Solidarity is reporting that I have the wrong version of React Native installed.

`✖ react-native: you have '21', but the project requires '^2.0.1'`

## Config

In my `.solidarity` file I have this:

```
    "React Native": [
      {
        "rule": "cli",
        "binary": "react-native",
        "semver": "^2.0.1",
        "platform": "darwin"
      }
    ],
```

## System Settings

```
System
  platform           darwin
  arch               x64
  cpu                8 cores                               Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz

JavaScript
  node               9.5.0        /usr/local/bin/node
  npm                5.6.0        /usr/local/bin/npm
  yarn               1.3.2        /usr/local/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.53.0

```

## Symptoms

From my shell, if I type `react-native --version` I get this:

![image](https://user-images.githubusercontent.com/68273/36597377-eb82b3ec-1876-11e8-9fe8-5d3767a7161b.png)

If I type: `./node_modules/.bin/react-native --version` I get this:

![image](https://user-images.githubusercontent.com/68273/36597398-02fda1bc-1877-11e8-9c32-d7cfbd23b165.png)

## Path Hijacking

When you `exec` a command with Node.JS, it **prepends** several node binary paths in front of anything that is defined in your shell.

That means `./node_modules/.bin/react-native` wins over `$(which react-native)`.

Which means our command output gets us:

```
Scanning folders for symlinks in /Users/steve/src/ir/clients/lanetix/node_modules (21ms)
0.53.0
```

Instead of 

```
react-native-cli: 2.0.1
react-native: 0.53.0
```

Which means [your regex](https://github.com/infinitered/solidarity/blob/8a0532debb97d07aa324a55786ff9ed124e83dbd/src/extensions/functions/removeNonVersionCharacters.ts#L3) is picking up the `(21ms)` part instead of the `0.53.0` part.

Giving you version 21 installed.

## Even If It Did Work...

Here's the fun part.

Let's say you put a `"line": 2` in your solidarity rule.

Now you get:

```
✖ react-native: you have '0.53.0', but the project requires '^2.0.1'
```

It's reporting the `react-native` dependency and not the `react-native-cli`.

Effectively, the `react-native-cli` becomes invisible unless you start mucking about with the `env.PATH` that `exec` uses.

## react-native-cli vs react-native

`react-native-cli` is only required to **create** a project.  If you are using `.solidarity`, you already have your project created... so this rule is kinda redundant if you already have a rule that checks for the presence of the `node_modules` directory.

I'm just going to delete the rule in my projects.

**Comment by GantMan** [comment]
Thanks for this report!  I'll work on getting around this issue.   If `which` gives me a path, and it's not the node injected path, I'm going to enforce we use that.  This should help fix that issue.

**Comment by skellock** [comment]
It'll give you `./node_modules/.bin/react-native`.

**Comment by GantMan** [comment]
I have how to do it.  It's (of course) disgusting and slow.

Here's my suggestion.

Do `which` and do a quick small check.  If I see `node_modules` in the results, immediately call my panic function and check if there's a global instead.  For CLI's prefer globals over local, and in verbose mode print a small message that we took such liberty.

This feels natural regarding I'm charged with CLI finding, and making decisions in that rule.  Can you think of a reason someone would want the node CLI OVER the global CLI when both are installed?  If so, I can add a flag like "fuckingnpm" or something in that vein.

**Comment by GantMan** [comment]
Notes for going after `node_modules`
Checking globals on npm:
`npm list -g --depth=0 --json`
> Returns JSON like you asked for

Checking globals on yarn
`yarn global list --depth=0 --silent --json`
> Returns JSON LINES, like a crazy person, including `activityTicks`

**Comment by skellock** [comment]
Another option is to change the `env.PATH` to slice off any path ending with `/node_modules/.bin`.

I'm not sure any other binary/lib works like this other than `react-native`.

**Comment by GantMan** [comment]
Cool.  I'm going to do my way which would "prefer global" but also fall back to node_modules should global not exist.

**Comment by GantMan** [comment]
@skellock - you're totally right.  I hit some serious performance issues asking for globals.  It turns out those commands I posted do API calls!  SUPER SLOW!  switching to your method.

**Comment by GantMan** [comment]
@skellock - I tested this on a dummy project, and as you can see it is able to take `rn` from global now.

So I can test line 1 and line 2 no problem, now.

This will be rolling out in the 2.0 update I'm slating for release.  Followed by the new features in the RN plugin, which are already sitting in a branch awaiting testing and use.

![working](https://user-images.githubusercontent.com/997157/36710381-2fb188da-1b43-11e8-8aba-6c3c6eedc2d7.gif)
