### ISSUE TITLE
Feature Request: inject wanted/installed versions into helpful error messages

### ISSUE THREAD

**Issue by tabrindle** [infinitered/solidarity#194]
Current example:

```
"requirements": {
    "npm": [
      {
        "rule": "cli",
        "binary": "npm",
        "semver": "~5.6.0",
        "error": "npm outdated: Update with `npm install -g npm@{version}`"
      }
    ]
}
```

When npm is out of date, it prints "npm outdated: Update with `npm install -g npm@{version}`" as expected. It would be awesome to be able to print a message like this:

"You have npm@5.6.0: Project requires 5.7.1. Update with `npm install -g npm@5.7.1`"

We could achieve this with a simple template, using ejs, handlebars, mustache, template literals/tagged templates, or even just find/replace.
```
"requirements": {
    "npm": [
      {
        "rule": "cli",
        "binary": "npm",
        "semver": "~5.6.0",
        "error": "You have npm@${installedVersion}: Project requires ${wantedVersion}. Update with `npm install -g npm@${wantedVersion}`"
      }
    ]
}
```

**Comment by GantMan** [comment]
closed by #195
