### ISSUE TITLE
Catch suffixes

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#20]
currently version crazed, not detecting things like `-beta` or `-rc1` etc. on versions.

Example fail:
![image](https://user-images.githubusercontent.com/997157/31049963-a4827c82-a604-11e7-99e7-db5de11f4518.png)

![image](https://user-images.githubusercontent.com/997157/31049971-b2a55776-a604-11e7-9a38-515b05648a59.png)

^ fix this

**Comment by tjwhalen16** [comment]
I've found the problem, and am almost done implementing a solution. Expect a pull request tomorrow October 1st.

**Comment by GantMan** [comment]
very cool!  yeah, I think some magic sprinkled on the regex would be a good fix.

**Comment by GantMan** [comment]
Closed by #20
