### ISSUE TITLE
Add CI property

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#208]
if I set `ci` to `false` in the JSON, then ignore that check when running on a machine where the environment has CI=true

This is needed because though a platform matches, some CI's don't have all the needed features.  Android/Environment etc.  So we'll flag these as OK on CI only.

**Comment by harrisrobin** [comment]
Has anyone figured out a workaround for now? 😄

**Comment by GantMan** [comment]
I'll see about adding this feature now.  Unless you are interested in how to do it @harrisrobin

**Comment by GantMan** [comment]
To @harrisrobin 's credit, 
![image](https://user-images.githubusercontent.com/997157/49330822-b6a59700-f559-11e8-9778-15e8a1c95ed3.png)

I'm trying to knock out some outstanding issues today, and I accidentally started with this one.  Kudos for the effort, and happy to help you with a separate PR if you're interested

**Comment by nonameolsson** [comment]
Would this be the correct usage? The following code fails when I run it as a part of my CI.

```json
    "Git Hooks": [
      {
        "rule": "shell",
        "command": "git config --local --get core.hooksPath",
        "match": ".githooks",
        "error": "Run `git config core.hooksPath .githooks` to add the Git Hooks to your project",
        "ci": false
      }
    ]
```

**Comment by GantMan** [comment]
@nonameolsson - what version do you have?

**Comment by nonameolsson** [comment]
@GantMan We use `2.3.1`.
