### ISSUE TITLE
Solidarity with TestFlight

### ISSUE THREAD

**Issue by BenCook28** [infinitered/solidarity#211]
I heard about Solidarity on React Native Radio, and appreciate the work you've done on solving a big problem.  A React Native app works on my phone with TestFlight, but much more slowly and crashes (possibly because of rapidly repeated presses) on a key stakeholder's phone.  The key stakeholder is not technical.  Would Solidarity be able to help me understand why it doesn't work as well on the stakeholder's phone?  I looked through the Solidarity repo and Googled "Solidarity with TestFlight" before posting this.

**Comment by GantMan** [comment]
Hrmmm, it's more of the developer environment than differences on phones.  Solidarity will be a poor tool for helping this.   I'm thinking instruments for iOS?

BTW, what phone does your stakeholder have?

**Comment by BenCook28** [comment]
Thanks for letting me know, GantMan.  The stakeholder has an iPhone X and I have an iPhone 8.  The issue seems to be that I have the most current iOS version on my phone and the stakeholder didn't.
