### ISSUE TITLE
Solidarity report shows double react-native 

### ISSUE THREAD

**Issue by bartolkaruza** [infinitered/solidarity#212]
Actual
Below report shows a double line for the react-native dependency, while running `solidarity report` on Bitrise. Also different versions are shown on each line.

Expected
only one version per binary

### Commands
| Binary        | Location                                          | Version   | Desired |
| ------------- | ------------------------------------------------- | --------- | ------- |
| watchman      | /usr/local/bin/watchman                           | 4.9.0     | *ANY*   |
| node          | /usr/local/bin/node                               | 8.9.1     | 10.4.1  |
| xcrun         | /usr/bin/xcrun                                    | 36        | 43      |
| code-push     | *MISSING*                                         | *UNKNOWN* | 2.1.8   |
| applesimutils | *MISSING*                                         | *UNKNOWN* | *ANY*   |
| npm           | /usr/local/bin/npm                                | 5.5.1     | 6.1.0   |
| detox         | /Users/vagrant/git/node_modules/.bin/detox        | *UNKNOWN* | *ANY*   |
| xcodebuild    | /usr/bin/xcodebuild                               | 9.2       | 9.3     |
| tsc           | /Users/vagrant/git/node_modules/.bin/tsc          | 2.9.1     | 2.6.2   |
| yarn          | /usr/local/bin/yarn                               | 1.3.2     | 1.3.2   |
| react-native  | /Users/vagrant/git/node_modules/.bin/react-native | 56        | 2.0.1   |
| react-native  | /Users/vagrant/git/node_modules/.bin/react-native | 0.55.4    | 0.55.4  |

**Comment by tabrindle** [comment]
Mind sharing your solidarity file? Looks like it's getting confused between the react native package and the cli.

**Comment by GantMan** [comment]
Ah, it's showing two because react-native has 2 outputs!

This is correct.

**Comment by GantMan** [comment]
I'm open to a better way to present this.  Please show in a new ticket for discussion.
