### ISSUE TITLE
No solidarity plugins found!

### ISSUE THREAD

**Issue by adrienthiery** [infinitered/solidarity#221]
Hi there,

Giving a try to solidarity, installed globally `solidarity` and `solidarity-react-native` then ran `solidarity snapshot` in a React Native project and I keep getting : 

```
$ solidarity snapshot                                                                                                                     ✔  09:16
? No `.solidarity` file found for this project.  Would you like to create one? true
-----------------------------------------------------------------------------------
Available technology plugins:

No solidarity plugins found!
      Add a plugin for a given technology:
      https://github.com/infinitered/solidarity/blob/master/docs/pluginsList.md
      OR write your own plugin for generating rules:
      https://github.com/infinitered/solidarity/blob/master/docs/plugins.md
      OR simply create a .solidarity rule-set by hand for this project:
      https://github.com/infinitered/solidarity/blob/master/docs/options.md

-----------------------------------------------------------------------------------
```

What am I missing ? 😕

**Comment by GantMan** [comment]
Strange it can't seem to find the plugin!!!!   It should have found it globally, but do you have `nvm` or something moving your globals?

Can you try installing `solidarity-react-native` locally and let me know if that works?  If it does then I just need to get the location where your global node modules are being installed and add that to the paths to check.

**Comment by adrienthiery** [comment]
Hey @GantMan ,
It does work when installed locally.

I use `yarn` to add global dependencies, so the plugin is indeed installed in `~/.config/yarn/global/node_modules/solidarity-react-native/`
