### ISSUE TITLE
The --solidarityFile doesn't work (in the current version published to NPM)

### ISSUE THREAD

**Issue by arizonatribe** [infinitered/solidarity#224]
Currently you have 2.1.0 published to NPM, however the `--solidarityFile` flag does not work with this version (although it was corrected when that logic was extracted to the [getSolidarityHelpers.ts file](https://github.com/infinitered/solidarity/commit/64fce79eb48e0d78d5639f0e8b1f8d360c23358f#diff-e1c9f6f455abdec2d5708fe5333227bb)).

When will you be publishing what you have on Github to NPM so that this flag will work correctly?

**Comment by arizonatribe** [comment]
If it's going to be awhile (looks like 6 months since your last release) perhaps you could remove that `--solidarityFile` from the Solidarity docs since it doesn't work?

**Comment by GantMan** [comment]
I plan on releasing 3.0 soon :)  maybe a month or so, would that be good?

**Comment by arizonatribe** [comment]
Yes that's fine. I'm trying to integrate solidarity into a forked version of `react-scripts` that will run before any build/start/test script is executed, and having a custom `.solidarity` per project would be ideal. For now I'm just doing a check if the `engines` prop from package.json that suffices

**Comment by GantMan** [comment]
@arizonatribe - can you let me know if 2.3.1 fixed this?  I released that version today.

**Comment by GantMan** [comment]
closing due to I'm sure 2.3.1 fixed this, and also, I'm about to release 3.0
