### ISSUE TITLE
Add `--no-color` option

### ISSUE THREAD

**Issue by cameronhunter** [infinitered/solidarity#239]
I'd like to save the contents of a solidarity report to a log file but it's saving the ansi color codes too. I've worked around the problem by piping it through [`strip-ansi-cli`](https://www.npmjs.com/package/strip-ansi-cli) but adding a `--no-color` option to `solidarity` would be perfect.

**Comment by GantMan** [comment]
Awesome, would this be something you're willing to PR?

**Comment by cameronhunter** [comment]
Following the this down the rabbit hole it turns out to be already supported!

`solidarity` uses [`GlueGunPrint`](https://github.com/infinitered/solidarity/blob/master/src/types.ts#L5) which uses [`colors`](https://github.com/infinitered/gluegun/blob/master/src/toolbox/print-tools.ts#L9) which supports passing [`--no-color`](https://github.com/Marak/colors.js/blob/master/README.md#disabling-colors) as a command line parameter.

It's great that this already works but it does feel fragile that a library a couple layers deep is parsing command line parameters. But, hey, the feature is there so thanks!
