### ISSUE TITLE
Published JSON schema on json.schemastore.org is outdated

### ISSUE THREAD

**Issue by shwanton** [infinitered/solidarity#247]
The current [published JSON schema](http://json.schemastore.org/solidaritySchema) does not reflect the latest [2.3.1 build](https://github.com/infinitered/solidarity/blob/v2.3.1/solidaritySchema.json)

Most notably, `shell` and `custom` definition types are missing.

There is probably a version flag I'm missing, but this is the one that is published in the [example](https://github.com/infinitered/solidarity/blob/master/.solidarity.example.json#L2)

**Comment by GantMan** [comment]
you're right.   Any interest in doing a PR?

**Comment by shwanton** [comment]
Merged! https://github.com/SchemaStore/schemastore/pull/785#issuecomment-524923471
