### ISSUE TITLE
version 3??

### ISSUE THREAD

**Issue by gwmccull** [infinitered/solidarity#249]
@GantMan any word on version 3? I saw you mention it a comment from months ago that it was nearly done

Any way I can help contribute? The current version is using some old packages with security issues and I may have trouble getting approval for v2.3.1 of solidarity

**Comment by GantMan** [comment]
YES!!!!!

Please do a full check of master.   I'm worried about it having some kind of bug, but honestly it needs a good once over.  What's in master might be ready to ship!

That's what's holding back the release.  I have tests, but I really want a human-checkthrough of the features and then it's good to release.  I've had 3 people volunteer to do this, and then it goes silent... I guess they never finish or do it.  So I forget until the next person comes along.

Today that's you :D

**Comment by petekp** [comment]
@GantMan Hi, just checking if v3 is still approaching release. There are several security issues in the current release — perhaps those could be resolved in a patch release?

**Comment by kevinvangelder** [comment]
We're working on fixing some issues prior to rollout in #253. Extra eyes on the code would be welcome.

**Comment by kevinvangelder** [comment]
@gwmccull My branch has been merged to master. Can you give it a try and let us know how it goes? If all is well we can probably release V3 by the end of the week.

**Comment by GantMan** [comment]
3 is out
