### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#25]
We need to help our Windows friends!   Linux/Mac support looks great, but you never know on window.  Let's check!

**Comment by murilodag** [comment]
Hello @GantMan,

Could you attach a demo file so I could check on Windows?

**Comment by GantMan** [comment]
Yup!   So here's a good demo file we keep on hand:
https://github.com/infinitered/solidarity/blob/master/.solidarity.example

This is currently ensuring the environment for a React Native project, but I'm sure with a slight adjustment it could be modified to be for any project environment needs.

**Comment by VerteDinde** [comment]
@GantMan I'm doing a lot of Windows testing in a VM as well; happy to be a second set of eyes and possibly help with any patches (though I don't want to step on your toes at all, @murilodag ) :smiley: 

Will test this tomorrow afternoon and report back.

**Comment by murilodag** [comment]
@GantMan, don't worry. =)

**Comment by GantMan** [comment]
btw, I've added some getting started with contributing docs.  Let me know if you have any questions.

**Comment by GantMan** [comment]
This was completed by @kevinvangelder
