### ISSUE TITLE
Friendly error not working for dir and file rule type

### ISSUE THREAD

**Issue by mishra-ankit** [infinitered/solidarity#256]
Version : 3.0.0

Steps :
- Create file or dir type rule with custom friendly error message.

```
{
  "requirements": {
    "TypeScript Active": [
      { "rule": "dir", "location": "./src1", "error": "Did you get this code from npm? Try GitHub!" },
      { "rule": "file", "location": "./1.txt", "error": "You don't have 1.txt. Go get it.!" }
    ]
  }
}
```
- run `solidarity`
- Both rules failed as expected. But doesn't print friendly error message.

Expected : 
Print user specified custom error message from rule.

Used to work in 2.3.1

**Comment by mishra-ankit** [comment]
I can create a PR for it.

**Comment by GantMan** [comment]
Thanks @mishra-ankit
