### ISSUE TITLE
High severity vulnerability in gluegun dependency (apisauce)

### ISSUE THREAD

**Issue by loiclouvet** [infinitered/solidarity#260]
Hello :)
Solidarity currently depends on gluegun@4.2.0 which depends on a version of axios with the high severity vulnerability https://www.npmjs.com/advisories/1594. Can we please upgrade gluegun to latest version ?

**Comment by GantMan** [comment]
Sounds good.   Do you want to do a PR?  If not I can put this on a TODO list.

**Comment by loiclouvet** [comment]
Hi @GantMan 
Sorry, didn't see your reply. I made a local PR but I'm waiting for this [MR](https://github.com/SimonJang/gluegun/commit/a411ecbf3805a57c8f5abeb69ef5450b155c329a) to be merged :)

**Comment by GantMan** [comment]
I merged that, now we'll just need a new version pushed and then an update.  Thanks!
