### ISSUE TITLE
Error after upgrading to 3.0.3

### ISSUE THREAD

**Issue by loiclouvet** [infinitered/solidarity#262]
Hello :)

After upgrading solidarity to 3.0.3, calling solidarity throw :
`env: node\r: No such file or directory`

Surely linked to #261

**Comment by GantMan** [comment]
Sorry!  I'll try to take a look at this ASAP.

@loiclouvet - would you be interested in getting access to help do releases?

**Comment by loiclouvet** [comment]
@GantMan I will try to have a look at this issue asap, I'm quite busy in those days...

**Comment by GantMan** [comment]
You've been invited to have write access to the repo.

I can add you to NPM as well, if you're interested.

**Comment by loiclouvet** [comment]
Seems to be linked to https://github.com/yarnpkg/yarn/issues/5480

**Comment by loiclouvet** [comment]
@GantMan Did you build last version with windows ?

**Comment by GantMan** [comment]
3.0.4 published from my mac.
