### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by robertherber** [infinitered/solidarity#268]
Just rediscovered this project after not using it for a few projects, and I'm a bit sad it doesn't seem to be maintained anymore.

Haven't really found a better alternative. We do have `react-native doctor` and `expo doctor`, but it's not very configurable, and I'd love to use something like this for Node/backend projects as well. Is there a more generally used package out there I've missed?

Some would-be-nices if this is still something to build on:
- Validate .nvmrc versions (currently it's not possible to compare cli output to a file, right?)
- Make it possible to use "cli doctor" tools like `react-native doctor` and `expo doctor` inside solidarity
- A plugin to warn when Windows line endings is about to cause problems 😄
- A plugin aimed at Expo

**Comment by GantMan** [comment]
Really appreciate you asking! Right now we are in sort of a “community support” mode, as we are focused on some other open source packages like [Ignite](https://github.com/infinitered/ignite) and [Reactotron](https://github.com/infinitered/reactotron). If you’re interested in contributing we’d love the help. No plans to sunset it anytime soon.
