### ISSUE TITLE
Add docs with some kind of tooling (e.g. Docsify)

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#30]
There needs to be clean way to read and understand how to use solidarity.  Preferably, I'd love to have something where I write markdown, and it generates the github site.

I'm looking into [Docsify](https://github.com/QingWei-Li/docsify) but could really use some help on setup for this portion of the app.  I'm terribly distracted while I'm working on the internals, so I haven't spent any time finding the best solution.

**Comment by rmnegatives** [comment]
I can give this a try. Ill give you a update soon.

**Comment by GantMan** [comment]
Sounds good @rmnegatives

**Comment by gabrielsclimaco** [comment]
@rmnegatives take a look at [jsdoc](http://usejsdoc.org/)

**Comment by rmnegatives** [comment]
@gabrielsclimaco jscode looks through js files and auto document Api.
It seems @GantMan is looking for something easier. Something that allows easy addition of .md files in one directory and easy serve on a website. 
Ive created a PR check it out this is start [PR](https://github.com/infinitered/solidarity/pull/32)
I will work on a suggested way to to format this.

**Comment by gabrielsclimaco** [comment]
@rmnegatives got it. Great job btw

**Comment by GantMan** [comment]
@rmnegatives - got a couple of comments on #33

**Comment by GantMan** [comment]
Closed by #32
