### ISSUE TITLE
Support for config files other than JSON?

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#31]
Solidarity isn't tech or system specific... should the config files be?

How about `.solidarity.yaml` and `.solidarity.json` and `.solidarity.toml`?

Basically, the file extension will tell solidarity HOW to read and write the file.  No need to force the users into JSON, and having those extensions will allow editors to easily colorize/check manual edits for errors. 

Feedback welcome!
cc: @skellock @jfairbank

**Comment by skellock** [comment]
My hot take: use `solidarity.json` and call it a day.

I noticed `.prettierrc` supports loading both `YAML` and `JSON` and I thought..... "oh... uh... cute.". Then went on with my day.

**Comment by GantMan** [comment]
I hate how JSON reads, and I also hate the lack of comments.

HDD (Hate Driven Development)

**Comment by skellock** [comment]
Then it sounds like you've decided?

**Comment by GantMan** [comment]
Hah, currently leaning towards, not for version 1.  Especially if I'm the most excited for the feature :D
