### ISSUE TITLE
Deterministic Version Finding

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#38]
Comes from convo on #23 - where code was adjusted to find the biggest version.

Consider this situation:
The CLI outputs 2 versions for some terrible reason.
On Alice's machine 1.0.1 and 0.47.2. Using your formula this would grab 0.47.2 and a person would ship that rule, happy it found the correct one.

Then on Bob's machine, he has 2 versions 2.0.0-beta and 0.47.2. On this machine, it would match 2.0.0-beta because it's longer.

Solution

By default, the tool should match the first identified semver. The user who is implementing a rule, knows this, and can always identify who will get matched.

We then provide a new property to a rule, perhaps matchIndex? Which is a bit harder to use than line, but properly so, it will help if for some reason there are multiple matches in output, that they can write a stable rule.

**Comment by GantMan** [comment]
I think I'm gonna knock this one out today.

**Comment by skellock** [comment]
Momma said knock this out!
