### ISSUE TITLE
Solidarity report and doctor

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#39]
### Soldiarity Report/Doctor
should use the `.solidarity` file to report the values of any given machine.

This would be ideal for people filing tickets.  If I identify my technology depends on 20 things in my `solidarity` file.  Then I could add "Please run `yarn solidarity report`" with my repo issue template, and it would give me results.   

Like `ignite doctor` but for free.

**Comment by GantMan** [comment]
### Goal - Incorporate Trevor's envInfo in this process.

Wish driven development
`solidarity report`

This will capture the OS from envinfo.  We should also grab arch & cpu (feature of envinfo?)  TODO for Trevor.
Then we will use gluegun's print.table (I think that's right - probably needs me to update it).   To outline the values of each item in the `.solidarity` requirements.  
 
* ENV will print their values, 
* CLI will print versions, 
* FILE/DIR will print their permissions/existence.

If a user types `solidarity report --verbose` we can include packages (provided by envinfo).

**Comment by tabrindle** [comment]
I think given PR-121 is merged we can probably close this. If there are outstanding issues/changes, we can create a different ticket?

**Comment by GantMan** [comment]
Let's do a quick meeting and jam on it, then close when we've written the next ticket.  Ping me on chat when you can.

**Comment by GantMan** [comment]
Lots of progress on this found in https://github.com/infinitered/solidarity/tree/report_update

Running `solidarity report` on a project produces:
```markdown
# ⚠️ Environment Report:
-----------------------------------------------------------------------------------
### System

| System Basics | Value                                         |
| ------------- | --------------------------------------------- |
| OS            | macOS High Sierra 10.13.1                     |
| CPU           | x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz |
| Report Info   | 11/27/2017, 12:33:30 AM (in 0.41s)            |


### Commands

| Binary        | Location                     | Version    | Desired    |
| ------------- | ---------------------------- | ---------- | ---------- |
| watchman      | /usr/local/bin/watchman      | 4.7.0      | *ANY*      |
| node          | /usr/local/bin/node          | 8.6.0      | 8.6.0      |
| applesimutils | /usr/local/bin/applesimutils | 0.5.12     | *ANY*      |
| xcrun         | /usr/bin/xcrun               | 35         | 35         |
| detox         | /usr/local/bin/detox         | *UNKNOWN*  | *ANY*      |
| emulator      | /usr/local/bin/emulator      | *UNKNOWN*  | *ANY*      |
| react-native  | /usr/local/bin/react-native  | 0.47.2     | 0.47.2     |
| code-push     | /usr/local/bin/code-push     | 2.0.1-beta | 2.0.1-beta |
| npm           | /usr/local/bin/npm           | 5.5.1      | 5.5.1      |
| xcodebuild    | /usr/bin/xcodebuild          | 9.1        | 9.1        |
| yarn          | /usr/local/bin/yarn          | 1.1.0      | 1.1.0      |


### Environment Variable

| Environment Var | Value                                |
| --------------- | ------------------------------------ |
| $ANDROID_HOME   | /usr/local/Cellar/android-sdk/24.4.1 |


### Filesystem

| Location       | Type | Exists |
| -------------- | ---- | ------ |
| ./package.json | File | ✔︎ YES |
| ./ios          | Dir  | ✔︎ YES |
| ./android      | Dir  | ✔︎ YES |


-----------------------------------------------------------------------------------
```

Which when pasted in github looks like so:
# ⚠️ Environment Report:
-----------------------------------------------------------------------------------
### System

| System Basics | Value                                         |
| ------------- | --------------------------------------------- |
| OS            | macOS High Sierra 10.13.1                     |
| CPU           | x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz |
| Report Info   | 11/27/2017, 12:33:30 AM (in 0.41s)            |


### Commands

| Binary        | Location                     | Version    | Desired    |
| ------------- | ---------------------------- | ---------- | ---------- |
| watchman      | /usr/local/bin/watchman      | 4.7.0      | *ANY*      |
| node          | /usr/local/bin/node          | 8.6.0      | 8.6.0      |
| applesimutils | /usr/local/bin/applesimutils | 0.5.12     | *ANY*      |
| xcrun         | /usr/bin/xcrun               | 35         | 35         |
| detox         | /usr/local/bin/detox         | *UNKNOWN*  | *ANY*      |
| emulator      | /usr/local/bin/emulator      | *UNKNOWN*  | *ANY*      |
| react-native  | /usr/local/bin/react-native  | 0.47.2     | 0.47.2     |
| code-push     | /usr/local/bin/code-push     | 2.0.1-beta | 2.0.1-beta |
| npm           | /usr/local/bin/npm           | 5.5.1      | 5.5.1      |
| xcodebuild    | /usr/bin/xcodebuild          | 9.1        | 9.1        |
| yarn          | /usr/local/bin/yarn          | 1.1.0      | 1.1.0      |


### Environment Variable

| Environment Var | Value                                |
| --------------- | ------------------------------------ |
| $ANDROID_HOME   | /usr/local/Cellar/android-sdk/24.4.1 |


### Filesystem

| Location       | Type | Exists |
| -------------- | ---- | ------ |
| ./package.json | File | ✔︎ YES |
| ./ios          | Dir  | ✔︎ YES |
| ./android      | Dir  | ✔︎ YES |


-----------------------------------------------------------------------------------


Special thanks to `envInfo`.   All I have left is finishing up tests.
