### ISSUE TITLE
Contribution Documentation. 

### ISSUE THREAD

**Issue by mattathompson** [infinitered/solidarity#40]
Having a hard time just setting up this repository locally w/ a passing test suite. It would be nice to have some sort of guidelines i.e: Node versioning and any other requirements.

**Comment by mattathompson** [comment]
More details: I get the same error when trying to run solidarity through the npm install -g as I do when trying to run the test suite. 

`
/opt/nodes/6.8.1/lib/node_modules/solidarity/src/index.js:3
module.exports = async () => {
                       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/nodes/6.8.1/lib/node_modules/solidarity/bin/solidarity:3:1)
    at Module._compile (module.js:570:32)
`

**Comment by GantMan** [comment]
Hey @mattathompson - what version of Node are you using?  You need node 7.6+

**Comment by mattathompson** [comment]
Perfect, I had it on `7.2.1`. I use _nodenv_ to manage versions.

**Comment by GantMan** [comment]
If 7.6 works for you, then I should consider some code that gives a warning to users.

Like "O SNAP! You'll need an upgraded Node to go any further"... or anything better than the message you got :)

**Comment by mattathompson** [comment]
Agreed. Need to update my nodenv package list and then I'll give it a try with the version you've suggested.

**Comment by mattathompson** [comment]
Updating to 7.6 solved all of my issues. Most definitely in favor of a friendly message when trying to run this package in an unsupported node version.

**Comment by GantMan** [comment]
I marked this issue for a PR for someone to add a friendly message in the docs.

I'll make a secondary issue for that (in code) friendly message.

**Comment by GantMan** [comment]
Closed by #43
