### ISSUE TITLE
Add `file` and `dir`rules.

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#47]
We're almost there!  1.0 release is coming up.  But we need to implement 2 simple rules to be 1.0 version complete.  Rule for checking if a file exists and rule for checking if a directory exists.

Both of these are 1 liners.  Rule descriptions found here:

https://github.com/infinitered/solidarity/blob/master/docs/options.md#rulefile
AND
https://github.com/infinitered/solidarity/blob/master/docs/options.md#ruledir

**Comment by ceejtron** [comment]
I'll take a stab at this.

**Comment by GantMan** [comment]
Looking great Christian!
