### ISSUE TITLE
Add Solidarity NPM badge to readme

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#48]
I just noticed there is no NPM badge for our latest version on the readme.

Super easy task.

**Comment by grigori-gru** [comment]
May I try to do this?

**Comment by GantMan** [comment]
I never realized how ugly the badges were on NPM!
Could you put the ugly NPM one at the bottom under a section for "Additional Info" and use badge.fury for the top?  

https://badge.fury.io/for/js/solidarity

**Comment by GantMan** [comment]
@yoavst and @grigori-gru - it looks like both of you are trying to do this task.  Not sure how to choose which one to accept, but hopefully one of you can make the adjustment I suggested above.

And for the other, I'll create another simple task, if that's ok.

**Comment by GantMan** [comment]
Closed by #51
