### ISSUE TITLE
Fix fail reporting

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#53]
As of right now when something fails it gets added to an array and printed out.  The printing isn't exactly as nice as it should be.
![image](https://user-images.githubusercontent.com/997157/31418956-8f786494-adfe-11e7-8684-212ecbebe342.png)
See?  We can make that grouping of errors on their own line at least... and definitely prettier.

**Comment by siakaramalegos** [comment]
I can take a stab at this. Did you have some phrasing ideas in mind?

**Comment by GantMan** [comment]
no phrasing in mind.  Try not to say the F word more than 3 times... and that's a soft requirement.

**Comment by siakaramalegos** [comment]
@GantMan lol... i will try my very best to minimize the f-bombs
