### ISSUE TITLE
Fixup Docs Site Dead Links

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#54]
There are 2 problems with the docs site:  https://infinitered.github.io/solidarity/#/

1. The site will not let you click on links inside the main page (e.g. try to click on `Solidarity Rules Options`)
1. We need to add those items to the left bar.   Probably time to add a `_sidebar.md` file like this: https://github.com/infinitered/gluegun/blob/master/docs/_sidebar.md, which powers the sidebar for the gluegun docs.

**Comment by thedeany** [comment]
I can take a look at this.
