### ISSUE TITLE
Make Contributors Guide

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#57]
It's not 100% clear on how someone should get started contributing.  Let's add that to the docs!

**Comment by ftonato** [comment]
I suggest this contributing guide:

```markdown
# CONTRIBUTING.md

When contributing to this repository, please first discuss the change you wish to make via issue,
email, or any other method with the owners of this repository before making a change. 

Please note we have a code of conduct, please follow it in all your interactions with the project.

## Pull Request Process

1. Ensure any install or build dependencies are removed before the end of the layer when doing a 
   build.
2. Update the README.md with details of changes to the interface, this includes new environment 
   variables, exposed ports, useful file locations and container parameters.
3. Increase the version numbers in any examples files and the README.md to the new version that this
   Pull Request would represent.
4. You may merge the Pull Request in once you have the sign-off of two other developers, or if you 
   do not have permission to do that, you may request the second reviewer to merge it for you.
```

**Comment by GantMan** [comment]
Hi @ftonato - I like where you're headspace is at but I have a few reservations on the above plan.

Most importantly in this doc, I'd like to have setup instructions for anyone who doesn't know how to pull the project down and actually run it.  Some people might not know what `npm link` is etc.

Regarding the PR process rules:
1. I'm not sure what item 1 is saying
1. Love this rule
1. I don't want anyone modifying the version numbers :)  That's just too personal, and my automatic versioning systems will bump those accordingly.  If others bump it, I have to bump it back down so as not to skip through the automated process.
1. Only IR folks + approved people will have merge permission, and I trust them enough not to have this as a rule.
