### ISSUE TITLE
Bring code coverage over 75%

### ISSUE THREAD

**Issue by GantMan** [infinitered/solidarity#62]
Wouldn't be hard at all to grab the low hanging fruit and make the code coverage less abysmal.

`yarn test` tells you where we're missing coverage.

**Comment by mattathompson** [comment]
:raised_back_of_hand:

**Comment by GantMan** [comment]
@mattathompson - would this task be easier for you in Jest?

**Comment by mattathompson** [comment]
@GantMan Yeah, probably. I might just be able to look into using something like `sinonjs`. I think converting the test suite over to jest could be a bit of overkill.

Don't let me be your blocker though. I'll be working on this during the evenings this week. So if you need faster turnaround I won't be offended.

**Comment by mattathompson** [comment]
Nice! I'm pulling the updates now.

**Comment by GantMan** [comment]
![giphy 3](https://user-images.githubusercontent.com/997157/32420518-070897f2-c251-11e7-9bbc-f44b5b1fe816.gif)

**Comment by skellock** [comment]
Good job guys!

**Comment by mattathompson** [comment]
Teamwork makes the dream work.

**Comment by skellock** [comment]
Found the sports fan!
