### ISSUE TITLE
Simpler Output

### ISSUE THREAD

**Issue by skellock** [infinitered/solidarity#85]
I'd love to see less verbose output by default.

### For Success

So if everything passes, instead of this:

![image](https://user-images.githubusercontent.com/68273/31841672-7c7cf5be-b5b8-11e7-919e-1e437a0da900.png)

Show this:

![image](https://user-images.githubusercontent.com/68273/31841685-938318d8-b5b8-11e7-803c-12e2f93c3fec.png)

I think it's important to show a success message instead of going full-on "Rule of Silence".

### For Failures

Instead of this:

![image](https://user-images.githubusercontent.com/68273/31841703-ab1da7ec-b5b8-11e7-93f5-241c127145c3.png)

Show this list of only the ones failling:

![image](https://user-images.githubusercontent.com/68273/31841706-b31f8442-b5b8-11e7-81d4-28b18844c37d.png)

And show the details behind `--details` or something.

😻

**Comment by GantMan** [comment]
Sounds good Steve!  Gonna mark this as a deliverable for v1

**Comment by Mknsri** [comment]
I'd love to take a crack at this.

**Comment by Mknsri** [comment]
I opened a pull request #89, hope it's OK

**Comment by GantMan** [comment]
Great work @Mknsri !
